eureka:
  instance:
    hostname: client
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.108.9.18:3306/hello?useSSL=false&characterEncoding=utf-8
    username: root
    password: sen515216
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
